name: test pwnshop
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 23
    steps:
      - uses: actions/checkout@v3
      - name: info
        run: |
          ls -alR
          git show
      - name: install
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip build-essential
          python -m pip install --upgrade pip
          pip install pytest pytest-dependency
          pip install .
      - name: test
        run: |
          pwnshop -c BabyShellBasicShellcode --src
          pwnshop -c BabyShellBasicShellcode --bin > babyshell_level1
          file babyshell_level1 | grep ELF
          pwnshop -c BabyShellBasicShellcode --verify
