name: test pwnshop
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 23
    steps:
      - uses: actions/checkout@v3
      - name: info
        run: |
          ls -lR
          git show
      - name: install
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-dev python3-pip build-essential libcapstone-dev
          python -m pip install --upgrade pip
          pip install pytest pytest-dependency
          pip install .
      - name: test
        run: |
          echo "pwncollege{TESTING}" | sudo tee /flag
          cd example_module
          pwnshop render ShellExample
          pwnshop build ShellExample > /tmp/shell_example
          file /tmp/shell_example | grep ELF
          pwnshop verify ShellExample
          pwnshop verify-module example_module
          cd ../../
          pwnshop -C pwnshop/example_module render ShellExample
